### ISSUE TITLE
The SCF procedure did not converge.

### ISSUE THREAD

**Issue by tmhuysen** [GQCG/hf#5]
I was presented with the following error:
`std::runtime_error: The SCF procedure did not converge.`

with the following xyz file
> 2
>
>N          0.00000       0.0          0.6125
>O          0.00000       0.0         -0.6125

and the following code    
` // Do a RHF calculation`
    `const std::string xyzfilename = "../exe/NO.xyz";`
    `double threshold = 1.0e-06;`
    `std::string basis_name = "STO-3G";`
    `libwint::Molecule helium (xyzfilename,+1);`
    `libwint::AOBasis ao_basis (helium, basis_name);`
    `ao_basis.calculateIntegrals();`
    `hf::rhf::RHF rhf (helium, ao_basis, threshold);`
    `rhf.solve();`

changing geometry to:
> 2
>
>N          0.00000       0.0          0.5
>O          0.00000       0.0         -0.5

worked, however i need to dissociate my molecule.

**Comment by lelemmen** [comment]
Apparently, I didn't let the user the option to specify a maximum number of iterations. Can you make a branch that does this, and set it to a higher number to see if you still have convergence issues?

**Comment by lelemmen** [comment]
Closing this issue because it has been resolved in the new code.
